SELECT DISTINCT
    EINE.SOURCE_SYSTEM,
    EINA.MATNR AS GMID,
    CASE 
        WHEN EINE.SOURCE_SYSTEM IS NULL OR TRIM(EINE.SOURCE_SYSTEM) = '' THEN 'UEBTK'
        ELSE 'UEBTK'
    END AS ATTRIBUTE,

    /* --- COMPLETENESS RULE: UEBTK present or missing --- */
    CASE 
        WHEN EINE.UEBTK IS NULL OR TRIM(EINE.UEBTK) = '' THEN 1
        ELSE 0
    END AS Completeness,

    /* --- ACCURACY RULE (UPDATED):
       Accuracy = 1 when:
       - PIR exists  (INFNR not null/blank)
       - AND UEBTK = 'X'
       Otherwise Accuracy = 0
    --- */
    CASE 
        WHEN (EINE.INFNR IS NOT NULL AND TRIM(EINE.INFNR) <> '')
             AND EINE.UEBTK = 'X'
        THEN 0
        ELSE 1
    END AS Accuracy

FROM SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_EXTENDED.VW_SRV_UNIFIED_EINE AS EINE
LEFT JOIN SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_EXTENDED.VW_SRV_UNIFIED_EINA AS EINA
    ON EINE.INFNR = EINA.INFNR
LEFT JOIN SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_UNIFIED.VW_SRV_UNIFIED_MARA AS MARA
    ON EINA.MATNR = MARA.MATNR