SELECT DISTINCT
    EINE.SOURCE_SYSTEM,
    EINA.MATNR AS GMID,
    CASE 
        WHEN EINE.SOURCE_SYSTEM IS NULL OR TRIM(EINE.SOURCE_SYSTEM) = '' THEN 'PEINH'
        ELSE 'PEINH'
    END AS ATTRIBUTE,

    /* --- COMPLETENESS RULE: PEINH present or missing --- */
    CASE 
        WHEN EINE.PEINH IS NULL OR TRIM(EINE.PEINH) = '' THEN 1
        ELSE 0
    END AS Completeness,

    /* --- ACCURACY RULE (UPDATED):
       Accuracy = 1 when:
       - PIR exists  (INFNR not null/blank)
       - AND PEINH >0
       Otherwise Accuracy = 0
    --- */
    CASE 
        WHEN (EINE.INFNR IS NOT NULL AND TRIM(EINE.INFNR) <> '')
             AND EINE.PEINH > 0
        THEN 0
        ELSE 1
    END AS Accuracy

FROM SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_EXTENDED.VW_SRV_UNIFIED_EINE AS EINE
LEFT JOIN SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_EXTENDED.VW_SRV_UNIFIED_EINA AS EINA
    USING (SOURCE_SYSTEM, INFNR)

WHERE EINE.SOURCE_SYSTEM IN ('P08', 'SHIFT')
   OR EINE.SOURCE_SYSTEM LIKE 'ATHENA%'