SELECT DISTINCT
    SOURCE_SYSTEM,
    GMID,
    'from_site' AS ATTRIBUTE,
    CASE
        WHEN FROM_SITE IS NULL THEN 1
        ELSE 0
    END AS COMPLETENESS,
    CASE
        WHEN LOWER(SPLIT_PART(FROM_SITE_UID, '_', 1)) = 'kinaxis'
         AND FROM_SITE <> SUBSTRING(FROM_SITE_UID, POSITION('_' IN FROM_SITE_UID) + 1)
        THEN 1
        ELSE 0
    END AS ACCURACY
FROM
    SHR_MS_PLANT_TO_MARKET_PROD.MS_PLANT_TO_MARKET_PROD_PBL_DQM.V_BILL_OF_DISTRIBUTION
WHERE SOURCE_SYSTEM IN ('kinaxis','KINAXIS')