SELECT DISTINCT
    EINE.SOURCE_SYSTEM,
    MARA.MATNR          AS GMID,
    'MINBM'             AS ATTRIBUTE,
    CASE
        WHEN EINE.MINBM IS NULL
          OR TRIM(EINE.MINBM) = '' THEN 1
        ELSE 0
    END AS Completeness,
    CASE
        WHEN EINE.MINBM IS NOT NULL
         AND ABS(EINE.MINBM) < 100000000
         AND ROUND(EINE.MINBM, 3) = EINE.MINBM
         AND MARC.BSTRF IS NOT NULL
         AND MARC.BSTRF <> 0
         AND ABS(MOD(EINE.MINBM, MARC.BSTRF)) < 1e-9
        THEN 0
        ELSE 1
    END AS Accuracy
FROM SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_EXTENDED.VW_SRV_UNIFIED_EINE  AS EINE
LEFT JOIN SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_EXTENDED.VW_SRV_UNIFIED_EINA AS EINA
    ON EINE.INFNR = EINA.INFNR
LEFT JOIN SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_UNIFIED.VW_SRV_UNIFIED_MARA  AS MARA
    ON EINA.MATNR = MARA.MATNR
LEFT JOIN SHR_HUB_SAP_PROD.HUB_SAP_PROD_SRV_MNS_UNIFIED.VW_SRV_UNIFIED_MARC  AS MARC
    ON EINA.MATNR = MARC.MATNR
   AND EINE.WERKS = MARC.WERKS